### ISSUE TITLE
Warning during wfacilo call

### ISSUE THREAD

**Issue by SebastienRietteMTO** [UMR-CNRM/EPyGrAM#2]
A warning is issued when converting the wfacilo output into array

EPyGrAM/epygram/formats/FA.py:793: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data, masked, masked_value = numpy.array(wfa.wfacilo(datasize,

**Comment by AlexandreMary** [comment]
Fixed in v-1.4.15
